[workspace]
resolver = "3"
members = ["protocol", "ingestor", "firmware"]

[workspace.dependencies]
protocol = { path = "protocol", default-features = false }

[profile.dev.package."*"]
opt-level = "s"   # optimize for size

[profile.dev]
panic = "abort"
opt-level = 1

[profile.release]
panic = "abort"
debug = 2
opt-level = "s"